# sppostls smartphone static relative batch-LS options

pos1-posmode       =static
pos1-frequency     =l1+l5
pos1-soltype       =forward
pos1-elmask        =25
pos1-snrmask_r     =off
pos1-snrmask_b     =off
pos1-ionoopt       =brdc
pos1-tropopt       =saas
pos1-sateph        =precise
pos1-posopt1       =off
pos1-posopt2       =off
pos1-posopt3       =on
pos1-posopt4       =on
pos1-posopt5       =on
pos1-posopt6       =on
pos1-exclsats      =
pos1-navsys        =125

pos2-armode        =instantaneous
pos2-gloarmode     =off
pos2-gpsarmode     =off
pos2-bdsarmode     =off
pos2-arfilter      =off
pos2-maxage        =30
pos2-syncsol       =off
pos2-slipthres     =0.05
pos2-rejionno      =30
pos2-rejgdop       =30
pos2-niter         =1
pos2-baselen       =0
pos2-basesig       =0

out-solformat      =llh
out-outhead        =on
out-outopt         =off
out-outvel         =off
out-timesys        =gpst
out-timeform       =tow
out-timendec       =3
out-degform        =deg
out-fieldsep       =
out-height         =ellipsoidal
out-solstatic      =single
out-outstat        =off

stats-eratio1      =300
stats-eratio2      =300
stats-eratio3      =300
stats-eratio4      =300
stats-eratio5      =300
stats-errphase     =0.006
stats-errphaseel   =0.006
stats-errphasebl   =0
stats-errdoppler   =1
stats-stdbias      =30
stats-stdiono      =0.03
stats-stdtrop      =0.3
stats-prnbias      =0.0001
stats-prniono      =0.001
stats-prntrop      =0.0001
stats-prnpos       =0
stats-clkstab      =5e-12

ant1-postype       =single
ant1-anttype       =*
ant1-antdele       =-0.027
ant1-antdeln       =0.077
ant1-antdelu       =-1.591

ant2-postype       =llh
ant2-pos1          =55.0122550194
ant2-pos2          =82.9850248083
ant2-pos3          =141.165
ant2-anttype       =*
ant2-antdele       =0
ant2-antdeln       =0
ant2-antdelu       =0
ant2-maxaveep      =0
ant2-initrst       =off

misc-timeinterp    =off
misc-rnxopt1       =
misc-rnxopt2       =
misc-pppopt        =

file-satantfile    =/Users/sergeidolin/SoCPP/src/igs20.atx
file-rcvantfile    =/Users/sergeidolin/SoCPP/src/igs20.atx
file-staposfile    =
file-geoidfile     =
file-ionofile      =
file-dcbfile       =
file-eopfile       =
file-blqfile       =
file-tempdir       =
file-geexefile     =
file-solstatfile   =
file-tracefile     =
file-gpt3file      =
